// react/components/sidenavs.tsx
import { PropsWithChildren, ReactNode, useState } from 'react';
import { AngelUIBaseProps } from './types';

type SideNavsProps = PropsWithChildren<AngelUIBaseProps<'sidenavs'> & {
  contents: {
    label: ReactNode,
    content: ReactNode
  }[],
  mainClassName?: string,
  contentWrapperClassName?: string
}>;

export function SideNavs(props: SideNavsProps) {
  const [activeNavs, setActiveNavs] = useState(0);

  return (
    <div
      data-aui-sidenavs
      className={props.mainClassName}
      data-aui-properties={typeof props.auiProperties === 'string' ? props.auiProperties : props.auiProperties?.join(' ')}
    >
      <nav data-aui-sidenavs-buttons>
        {props.contents.map(({ label }, i) => (
          <button key={i} data-aui-sidenavs-button={activeNavs === i ? 'active' : 'inactive'} onClick={() => setActiveNavs(i)}>{label}</button>
        ))}
      </nav>
      <div data-aui-sidenavs-contents className={props.contentWrapperClassName}>
        {props.contents.map(({ content }, i) => (
          <div key={i} data-aui-sidenavs-content={activeNavs === i ? 'active' : 'inactive'}>{content}</div>
        ))}
      </div>
    </div>
  );
}

// solid-js/components/sidenavs.tsx
import { ParentProps, JSXElement, createSignal } from 'solid-js';
import { AngelUIBaseProps } from './types';

type SideNavsProps = ParentProps<AngelUIBaseProps<'sidenavs'> & {
  contents: {
    label: JSXElement,
    content: JSXElement
  }[],
  mainClass?: string,
  contentWrapperClass?: string
}>;

export function SideNavs(props: SideNavsProps) {
  const [activeNavs, setActiveNavs] = createSignal(0);

  return (
    <div
      data-aui-sidenavs
      class={props.mainClass}
      data-aui-properties={typeof props.auiProperties === 'string' ? props.auiProperties : props.auiProperties?.join(' ')}
    >
      <nav data-aui-sidenavs-buttons>
        {props.contents.map(({ label }, i) => (
          <button data-aui-sidenavs-button={activeNavs() === i ? 'active' : 'inactive'} onClick={() => setActiveNavs(i)}>{label}</button>
        ))}
      </nav>
      <div data-aui-sidenavs-contents class={props.contentWrapperClass}>
        {props.contents.map(({ content }, i) => (
          <div data-aui-sidenavs-content={activeNavs() === i ? 'active' : 'inactive'}>{content}</div>
        ))}
      </div>
    </div>
  );
}
