// react/components/form/types.ts
import { ComponentProps, PropsWithChildren } from 'react'

export type FormFieldBaseProps = {
  name?: string,
  // arbitrary
  label?: string,
}

export type TextFieldProps = FormFieldBaseProps & {
  labelClassName?: string,
  wrapperClassName?: string,
  onChange?: ComponentProps<'input'>['onChange']
}

export type TextAreaProps = FormFieldBaseProps & {
  labelClassName?: string,
  wrapperClassName?: string,
  inputClassName?: string,
  onChange?: ComponentProps<'textarea'>['onChange']
}

export type SelectFieldProps = FormFieldBaseProps & PropsWithChildren<{
  labelClassName?: string,
  wrapperClassName?: string,
  inputClassName?: string,
  onChange?: ComponentProps<'select'>['onChange']
}>

export type RadioButtonProps = FormFieldBaseProps & {
  labelClassName?: string,
  wrapperClassName?: string,
  inputClassName?: string,
  onChange?: ComponentProps<'input'>['onChange']
}

export type CheckBoxProps = FormFieldBaseProps & {
  labelClassName?: string,
  wrapperClassName?: string,
  inputClassName?: string,
  onChange?: ComponentProps<'input'>['onChange'],
  checked?: boolean,
}

export type FileInputProps = FormFieldBaseProps & {
  labelClassName?: string,
  wrapperClassName?: string,
  inputClassName?: string,
  onChange?: ComponentProps<'input'>['onChange'],
}

// solid-js/components/form/types.ts
import { JSX, ParentProps } from 'solid-js'

export type FormFieldBaseProps = {
  name?: string,
  // arbitrary
  label?: string,
}

export type TextFieldProps = FormFieldBaseProps & {
  labelClass?: string,
  wrapperClass?: string,
  onChange?: (e: Event & { currentTarget: HTMLInputElement, target: Element }) => void
}

export type TextAreaProps = FormFieldBaseProps & {
  labelClass?: string,
  wrapperClass?: string,
  inputClass?: string,
  onChange?: JSX.ChangeEventHandlerUnion<HTMLTextAreaElement, Event>
}

export type SelectFieldProps = FormFieldBaseProps & ParentProps<{
  labelClass?: string,
  wrapperClass?: string,
  inputClass?: string,
  onChange?: JSX.ChangeEventHandlerUnion<HTMLSelectElement, Event>
}>

export type RadioButtonProps = FormFieldBaseProps & {
  labelClass?: string,
  wrapperClass?: string,
  inputClass?: string,
  onChange?: (e: Event & { currentTarget: HTMLInputElement, target: Element }) => void,
}

export type CheckBoxProps = FormFieldBaseProps & {
  labelClass?: string,
  wrapperClass?: string,
  inputClass?: string,
  onChange?: (e: Event & { currentTarget: HTMLInputElement, target: Element }) => void,
  checked?: boolean,
}

export type FileInputProps = FormFieldBaseProps & {
  labelClass?: string,
  wrapperClass?: string,
  inputClass?: string,
  onChange?: (e: Event & { currentTarget: HTMLInputElement, target: Element }) => void,
}
